import React, { useState } from 'react'
import Head from 'next/head'
import { Header, CartSidePanel } from '../components/index'

export default function Home() {

  const [cartPanel, setCartPanel] = useState(false)

  return (
    <div>
      <Head>
        <title>NextStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Header setCartPanel={setCartPanel} />
      <CartSidePanel cartPanel={cartPanel} setCartPanel={setCartPanel} />
      <main>

      </main>

      <footer>

      </footer>
    </div>
  )
}
