import React, { useState } from 'react'
import Head from 'next/head'
import { 
  Header,
  Hero, 
  CartSidePanel, 
  Footer 
} 
from '../components/index'

export default function Home() {

  const [cartPanel, setCartPanel] = useState(false)

  return (
    <div>
      <Head>
        <title>NextStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <CartSidePanel cartPanel={cartPanel} setCartPanel={setCartPanel} />

      <Header setCartPanel={setCartPanel} />
      <Hero />
      <main>

      </main>

      <Footer />
    </div>
  )
}
