import React from 'react'
import Head from 'next/head'
import { Header } from '../components/index'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>

      </main>

      <footer>

      </footer>
    </div>
  )
}
